---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	extract_topic(extract_topic)
	cat(cat)
	dog(dog)
	unsupported(unsupported)
	__end__([<p>__end__</p>]):::last
	__start__ --> extract_topic;
	extract_topic -.-> cat;
	extract_topic -.-> dog;
	extract_topic -.-> unsupported;
	cat --> __end__;
	dog --> __end__;
	unsupported --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
